# https://nix.dev/guides/recipes/continuous-integration-github-actions.html
name: test goboscript nix flake

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - run: |
        bash <(curl -L https://nixos.org/nix/install)
        nix-env -iA devenv -f https://github.com/NixOS/nixpkgs/tarball/nixpkgs-unstable
