# https://nix.dev/guides/recipes/continuous-integration-github-actions.html
name: test goboscript nix flake

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - run: echo hello world
