# https://nix.dev/guides/recipes/continuous-integration-github-actions.html
# https://devenv.sh/integrations/github-actions/#introduction
name: test goboscript nix flake

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v16
      with:
        name: igs
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    # - name: Install devenv.sh
    #   run: nix profile add nixpkgs#devenv
    # - name: Build the devenv shell and run any git hooks
    #   run: devenv test
    # - name: Run a single command in the devenv shell
    #   run: devenv shell hello
    # - name: Run a multi-line command in the devenv shell
    #   shell: devenv shell bash -- -e {0}
    #   run: |
    #     hello
    #     say-bye
    - name: Run command in flake shell
      shell: bash -c "nix develop --impure -c bash -- {0}"
      run: | 
        goboscript help

